/*

Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"
Output:
e
Explanation:
'e' is the letter that was added.

*/



#include <iostream>
#include <algorithm>

using namespace std;


// Sort first and then find one different character
char findTheDifference(string s, string t) {

    sort(s.begin(), s.end());
    sort(t.begin(), t.end());

    int i = 0;
    while (s[i] == t[i]){
        ++i;
    }

    return t[i];

}


int main() {

    string s = "asdfghjkl";
    string t = "lkjhgfdswa";

    char output = findTheDifference(s,t);
    cout << "OUTPUT " << output << endl;


}